@startuml

participant child_process
participant parent_process

hnote over parent_process
get version info from versions.json
endnote

alt loop versions number
parent_process -> child_process: fork process & save proccess version data
activate parent_process
activate child_process

hnote over child_process
pass client event 
(prevent crash with legacy process)
endnote

parent_process -> child_process: send path and rule

parent_process -> child_process: send legacy process user data (default [] )

deactivate child_process
deactivate parent_process

hnote over child_process
preparing client listen or another process interact by path
(prevent crash with legacy process)
endnote

hnote over child_process
listen client event
(pass using legacy process client user )
endnote

end
