@startuml

participant process

participant management

management -> process : process.exit request

process -> process : check queue

process -> management : send processing queue list

new_process <- management : send processing queue list

management -> process : check processing queue request per ten seconds
activate process


process -> management : send processing queue
activate management

management -> new_process : send processing queue

process -> management : finish queue and exit
deactivate process
deactivate management